# 简化的分析选项 - 用于解决VS Code 1000+错误问题
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 基本规则 - 只保留最重要的
    prefer_single_quotes: true
    avoid_print: false  # 开发阶段允许使用print
    prefer_const_constructors: true
    use_key_in_widget_constructors: true
    
    # 性能相关 - 必要的优化
    avoid_function_literals_in_foreach_calls: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    
    # 可读性 - 基本的代码质量
    avoid_unnecessary_containers: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_final_locals: true
    
    # 错误预防 - 重要的
    use_build_context_synchronously: true
    avoid_returning_null_for_void: true
    
analyzer:
  # 强制类型检查 - 但不要太严格
  strong-mode:
    implicit-casts: true    # 允许隐式类型转换
    implicit-dynamic: true  # 允许隐式dynamic类型
    
  # 排除生成的文件
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/generated/**"
    - "**/build/**"
    - "**/.dart_tool/**"
    
  # 错误级别设置 - 更宽松
  errors:
    # 关键错误保持为错误
    missing_return: error
    
    # 其他降级为警告或忽略
    unused_import: warning
    unused_local_variable: warning
    unused_field: warning
    unused_element: warning
    
    # 完全忽略这些
    todo: ignore
    fixme: ignore
    invalid_annotation_target: ignore
    depend_on_referenced_packages: ignore